<?php
return [
    'adminEmail' => 'admin@example.com',
    'baseUrl' => '',
    'htmlUrl' => '/html',
    'SMS_SN' => 'DXX-WSS-100-10994',
    'SMS_SIG' => '申友国际教育',
    'SMS_PWD' => '057499',
    'timeLimit' => 600,
    'phone2' => '您正在通过手机预约申友网留学顾问！',
    'phone1' => '您正在通过手机免费获取留学评估报告！',
    'phone3' => '您正在通过手机预约申友网考试培训顾问！',
    'phone4' => '您正在通过手机免费注册申友网公开课会员！',
    'phone5' => '您正在通过手机找回申友公开课账号密码！',
    'phone6' => '您正在通过邮箱免费注册申友网公开课会员！',
    'phone7' => '您正在通过邮箱找回申友公开课账号密码！',
    'phone8' => '您正在修改绑定手机！',
    'phone9' => '您正在修改绑定邮箱！',
    'schoolUrl' => 'http://schools.smartapply.cn/cn/api/school',
    'categoryUrl' => 'http://schools.smartapply.cn/cn/api/cats',
    'contentUrl' => 'http://schools.smartapply.cn/cn/api/content',
    'schoolConnect' => 'http://schools.smartapply.cn',
    'question' => [
        1=>'服务流程',
        2=>'出国考试课程',
        3=>'选校定位',
        4=>'推荐顾问',
        5=>'服务流程',
        6=>'申请步骤',
        7=>'申请费用',
        8=>'奖学金',
        9=>'其他',
    ],
    'service' => [
        1=>'半div',
        2=>'文书写作与精修',
        3=>'学长学姐选校指导',
        4=>'全套留学服务',
        5=>'已找中介',
    ],
    'company' => [
        1=>'500强',
        2=>'四大',
        3=>'外企',
        4=>'国企',
        5=>'私营企业',
    ],
    'school' => [
        1=>'清北复交浙大',
        2=>'985',
        3=>'211',
        4=>'非211本科',
        5=>'专科',
    ],
    'country' => [
        155=>'美国',
        156=>'英国',
        157=>'加拿大',
        158=>'澳洲',
        159=>'新加坡',
        160=>'香港',
        520=>'欧洲',
        521=>'亚洲',
    ],
];
